### ISSUE TITLE
:rocket: crap

### ISSUE THREAD

**Issue by thinq4yourself** [BeardandFedora/writeon.io#10]
One must be careful not to .gitignore an `app` directory and thus remove the app from source control. I will be fixing this and correcting the process as to help avoid this in the future. 

> However, I assigned to beard to make a point to let you know about this. The [latest commit](https://github.com/BeardandFedora/writeon.io/commit/dcb138eb0066f34d8e2b4dae39817dc8e108a60b) has removed your wee lil app due to a pretty substantial error in the gitignore flow.

**Comment by thinq4yourself** [comment]
### Resetting to the last, most proper point in history: fb1d3aa288357d3fffe83c560164290fa0b00a28

### Local reset:

`$ git reset --hard fb1d3aa`

### Remote reset:

`$ git push -f origin fb1d3aa:master`

### Local fixes and bring up to date:

`$ git add --all`
`$ git commit -m "the change log"`
`$ git push origin master`

> This is going to rewrite history. You may be disappointed in the future. See you in the past.

**Comment by thinq4yourself** [comment]
See above comment, which closes this issue

**Comment by yaboi** [comment]
Ah, yes. The app and test folders were being ignored for a push to heroku. While the dist folder and newrelic.js file were being ignored for a push to github.

Wasn't a mistake, just a lack of documentation up and beyond the `#Uncomment to push to heroku` and `#Uncomment to push to github` inline in the .gitignore file.
