### ISSUE TITLE
Marketing lingo tense (past/present)?

### ISSUE THREAD

**Issue by yaboi** [BeardandFedora/writeon.io#19]
For instance, "WriteOn was conceived by people who..." Should we use past tense or present tense? WriteOn WAS or WriteOn IS conceived by people who...

Does past tense make it sound like it's complete, done, and never changing. Or does present tense make it sound like it's not ready yet, ever changing and unstable?

**Comment by thinq4yourself** [comment]
IS.

**Comment by yaboi** [comment]
List of updates where needed. Replace as time permits and whoever can allot the time

**/home**
- "_We've_ refined the typical writing interface..." ---> "_We_ refined the typical writing interface..."

**/features**
- "WriteOn _was_ conceived by people who need to write." ---> "WriteOn is conceived by people who need to write." *Note: "WriteOn is conceived" is used twice in that one paragraph.
- "_We've used_ a proven method to edit and publish..." ---> "_We use_ a proven method to edit and publish..."
