### ISSUE TITLE
Google Tag Manager error

### ISSUE THREAD

**Issue by yaboi** [BeardandFedora/writeon.io#25]
Currently receiving a 404 error message for the Google Tag Manager script.

> GET https://www.googletagmanager.com/gtm.js?id=GTM-TC7CFS 404 (Not Found)

**Comment by thinq4yourself** [comment]
Beats me :confused: 

https://developers.google.com/tag-manager/quickstart

> Yaboi can also access Google Tag manager and take a look at the WriteOn container code.

OK, had to create a tag and publish the container before it works on the page.
