### ISSUE TITLE
Remove AngelList console.log(CTA) for job listings

### ISSUE THREAD

**Issue by yaboi** [BeardandFedora/writeon.io#29]
The console currently spits out:

> Do you have a great idea that would make AngelList better?  Want to implement it?  We’re always hiring: https://angel.co/angellist/jobs

Free console adverts with plugin install. Smooth operators.

**Comment by thinq4yourself** [comment]
Holy shitsu :dog2:. Smooth indeed. We should do that.

**Comment by yaboi** [comment]
Ha, I love all your markdown emoji's. :metal:
