### ISSUE TITLE
Add "X" functionality to MailChimp error 'alert' on main.html

### ISSUE THREAD

**Issue by yaboi** [BeardandFedora/writeon.io#3]
Currently, there is no angular functionality implemented for the "X" when an error is returned from MailChimp and an alert is shown.

See: http://angular-ui.github.io/bootstrap/#/alert

**Comment by thinq4yourself** [comment]
Doesn't seem to work on mobile.

**Comment by yaboi** [comment]
Very interesting.

Noted... I'm looking at it in Chrome's device mode. Doesn't work there either, so I'll be able to debug easily.
