### ISSUE TITLE
Strip down the "Welcome" email from a user signing up

### ISSUE THREAD

**Issue by yaboi** [BeardandFedora/writeon.io#30]
After much deliberation, it has been decided that this ticket belongs in github! W00t!

Example email I received from [Sniply](http://snip.ly/) after signing up:

> "Hey Tyler!
> 
> I've put a lot of time and effort into building Sniply—but I know it's not perfect. As you play around with it, could you keep me posted on what you think?
> 
> Oh, and be sure to check out our browser plugin. It integrates with Buffer/Hootsuite and a bunch of other platforms. We've got Chrome Extension, Firefox Extension, and another one for Safari coming soon.
> 
> Keep me posted, okay? Thanks!
> 
> Sincerely, 
> Mike @Sniply"

Layman, transparent, clear call-to-actions without being "marketing-y". All around, I like it.

**Ask: Should we strip down the current "welcome" email (and all around on boarding messaging) to be more streamlined like this?**

**Comment by thinq4yourself** [comment]
Yes. Go forth and be awesome.

**Comment by thinq4yourself** [comment]
As if there's any doubt.

**Comment by yaboi** [comment]
:metal: (my new favorite emoji, obviously)
