### ISSUE TITLE
Host Variant Pages In-App

### ISSUE THREAD

**Issue by thinq4yourself** [BeardandFedora/writeon.io#45]
This one's for you @yaboi ....
I have created Variant middleware that allows us to launch and host Variant pages at writeon.io/*.

Since writeon.io relies on SSL, Variant is also receiving an SSL upgrade (24 hours to complete DNS propagation), but afterwards we will be able to call Variant resources in our pages using SSL by use of `//`. RIght now, the pages won't load until DNS changes & SSL cert is finished (by 5/15/15).

The middleware is in `web.js`. The new pages are in `app/variants`. Grunt has been updated to handle variants in the build process, which includes any custom assets like `images` and `css`. It's pretty sick.

First pages to launch using this middleware are [writeon.io/for/travel-writers](http://writeon.io/for/travel-writers) and [writeon.io/for/ebook-authors](http://writeon.io/for/ebook-authors).

This has been tested in dev and works great.

**Comment by yaboi** [comment]
This also wipes out an issue tracked in WriteOnApp repo (https://github.com/BeardandFedora/WriteOnApp/issues/5)
