### ISSUE TITLE
Update MC autoresponders & create onboarding campaigns

### ISSUE THREAD

**Issue by thinq4yourself** [BeardandFedora/writeon.io#46]
I think now is a good time for us to start talking to the awesome people who signup, wherever we can.  I remember you really liked the Sniply drip emails, so let's roll with it.

Please update the MC taking into account the following:
1. These correspond to the current signup process on the main site, starting with email address in the beta signup list in MC.
2. Update the `Confirmation Email` and `Final Welcome Email` templates, as appropriate [design/mesg]
3. Update remaining the custom list templates to each step in the `List`, and test
4. Create a new drip campaign as a "Hey there new user", and schedule for 3 days from now emailing to everyone in the signup list
5. Create additional drip campaigns intended to keep them using WriteOn, such as day 7, day 12, day 21, sent only to users in previous send out. Repeat this using MC option to `Send to new signups only`
6. Suggest in each drip campaign to use the UserVoice tools anytime for feedback/ideas
7. The final one should focus on a CTA, asking them for something, be it upgrade, promote, share, quote, etc.
8. See if we can get this question answered: "What would it take to get you to use WriteOn every day"

**Comment by yaboi** [comment]
I agree with this completely and believe it is something that we should focus on immediately after the "Get 200" campaign is completely launched and solid.

I've added a Trello card for further discussion on specifics of the email campaign.

**Comment by yaboi** [comment]
Here's the "welcome" email I received from Sniply as a point of reference:

>Hey Tyler!  

>I've put a lot of time and effort into building Sniply—but I know it's not perfect. As you play around with it, could you keep me posted on what you think?

>Oh, and be sure to check out our browser plugin. It integrates with Buffer/Hootsuite and a bunch of other platforms. We've got Chrome Extension, Firefox Extension, and another one for Safari coming soon.

>Keep me posted, okay? Thanks!

>Sincerely, 
>Mike @Sniply

An example of how we can utilize this is:

>Hey there,

>(We've/I've) put a lot of time and effort into building WriteOn and (we/I) know it's not perfect. As you continue writing, could you keep (us/me) posted on what you think?

>Oh, and be sure to check out our automated publishing. You can publish directly from WriteOn to platforms like WordPress, Blogger, Tumblr, Google Drive, and Github. Or, you can just sync what you write with the WriteOn cloud.

>Keep (us/me) posted, okay? Thanks!

>Cheers,
>(<3/Tyler/Team) @WriteOnApp

I think using an "I" approach rather than a "we" approach is much more personal. But, I WOULD much rather have people contacting "WriteOn" vs. "Tyler." Thoughts?
