### ISSUE TITLE
"Thank You" page after signup

### ISSUE THREAD

**Issue by yaboi** [BeardandFedora/writeon.io#6]
Redirect a user to a "Thank You" page that focuses on converting into the app. Page could include "More Features", "What To Expect Next", etc.

All content should be focused at building interest in continuing into the on-boarding process (i.e. no links to blog, social, or anything that will distract from funnel.)

> # 7: Use the Thank You Page
> 
> When someone does sign up to your blog, take them to a killer “Thank You” page that references the app with screenshots to highlight the benefits. - [An Epic List of 100 Growth Hacks](http://www.searchenginejournal.com/epic-list-100-growth-hacks-startups/118690/)

_Note: This page is not for brand awareness . It should be strictly focused and part of the on-boarding process. NO DISTRACTIONS._

**Comment by thinq4yourself** [comment]
Would :heart: to see it in action!
